Feature/buildwithenvironments
rdkcentral/Lightning-CLI pull request #122
Opened 2021-03-09 10:40 UTC by sandeep-vedam

Following are the changes in this PR : 
1. Added support for different environments(settings).

2021-03-15 20:45 UTC, michielvandergeest requested changes
Looks good! Can we also implement this for the `dist` command (in `src/helpers/dist.js`)?

2021-03-16 07:48 UTC, sandeep-vedam commented
> Looks good! Can we also implement this for the `dist` command (in `src/helpers/dist.js`)?

Hey @michielvandergeest ,

I have implemented this for 'dist' command too.

2021-04-23 14:20 UTC, michielvandergeest approved these changes
LGTM

2021-04-23 14:26 UTC, michielvandergeest approved these changes

2021-04-23 14:26 UTC, merged